import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FAFAFA',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  backButton: {
    padding: 8,
  },
  backButtonText: {
    fontSize: 16,
    color: '#FF7B00',
    fontWeight: '600',
  },
  title: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1A1A1A',
  },
  placeholder: {
    width: 60,
  },
  multiSelectButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFF3E6',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FFD9B3',
  },
  multiSelectButtonActive: {
    backgroundColor: '#FF7B00',
    borderColor: '#FF7B00',
  },
  recentSection: {
    paddingTop: 8,
  },
  recentHint: {
    fontSize: 11,
    color: '#9CA3AF',
    paddingHorizontal: 4,
    marginBottom: 4,
    fontStyle: 'italic',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1A1A1A',
    paddingHorizontal: 4,
    marginBottom: 8,
  },
  recentList: {
    paddingHorizontal: 0,
  },
  recentCompactColumn: {
    justifyContent: 'flex-start',
    marginHorizontal: 4,
    gap: 6,
  },
  recentCompactItem: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 2,
    elevation: 1,
  },
  recentCompactRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  recentCompactRowPinned: {
    borderLeftWidth: 2,
    borderLeftColor: '#FF7B00',
    paddingLeft: 4,
  },
  pinBadge: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#FF7B00',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
  },
  recentCompactInfo: {
    marginRight: 10,
    flexShrink: 1,
  },
  recentCompactName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1A1A1A',
    marginBottom: 1,
  },
  recentCompactCalories: {
    fontSize: 11,
    color: '#FF7B00',
  },
  recentCompactButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    marginLeft: 'auto',
  },
  recentCompactUom: {
    fontSize: 9,
    color: '#999999',
    marginRight: 2,
  },
  recentQuickBtn: {
    paddingVertical: 3,
    paddingHorizontal: 6,
    borderRadius: 4,
    backgroundColor: '#F5F5F5',
    minWidth: 24,
    alignItems: 'center',
  },
  recentQuickBtnHovered: {
    backgroundColor: '#FFE0B2',
  },
  recentQuickBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#666666',
  },
  recentQuickBtnTextHovered: {
    color: '#FF7B00',
  },
  listHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 4,
    paddingVertical: 12,
  },
  sectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  resultCount: {
    fontSize: 14,
    color: '#666666',
  },
  list: {
    paddingHorizontal: 12,
    paddingBottom: 24,
  },
  row: {
    justifyContent: 'space-between',
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 48,
  },
  emptyText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#666666',
    marginTop: 16,
  },
  emptySubtext: {
    fontSize: 14,
    color: '#999999',
    marginTop: 4,
    textAlign: 'center',
    paddingHorizontal: 20,
  },
  // Online Search Styles
  searchOnlineButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    backgroundColor: '#FF7B00',
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 12,
    marginTop: 20,
    minWidth: 180,
  },
  searchOnlineText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  onlineNote: {
    fontSize: 12,
    color: '#999999',
    marginTop: 12,
    textAlign: 'center',
  },
  onlineSection: {
    flex: 1,
  },
  loadingState: {
    alignItems: 'center',
    paddingVertical: 48,
  },
  loadingText: {
    fontSize: 16,
    color: '#666666',
    marginTop: 16,
  },
  onlineResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 12,
    marginHorizontal: 16,
    marginVertical: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  onlineResultImage: {
    width: 50,
    height: 50,
    borderRadius: 8,
    marginRight: 12,
    backgroundColor: '#F5F5F5',
  },
  onlineResultInfo: {
    flex: 1,
    marginRight: 12,
  },
  onlineResultName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#1A1A1A',
  },
  onlineResultBrand: {
    fontSize: 12,
    color: '#666666',
    marginTop: 2,
  },
  onlineResultSource: {
    fontSize: 10,
    color: '#999999',
    marginTop: 4,
  },
  onlineResultCalories: {
    alignItems: 'center',
    backgroundColor: '#E8F5E9',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  onlineResultCalorieValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#4CAF50',
  },
  onlineResultCalorieUnit: {
    fontSize: 10,
    color: '#66BB6A',
  },
  backToLocalButton: {
    flexDirection: 'row',
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backToLocalText: {
    fontSize: 14,
    color: '#FF7B00',
    fontWeight: '600',
  },
  loadingMore: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 16,
    gap: 8,
  },
  loadingMoreText: {
    fontSize: 13,
    color: '#999',
  },
  recentHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 4,
    marginBottom: 8,
  },
  emptyHomeState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 64,
  },
  emptyHomeText: {
    fontSize: 17,
    fontWeight: '600',
    color: '#9CA3AF',
    marginTop: 14,
  },
  emptyHomeSubtext: {
    fontSize: 13,
    color: '#D1D5DB',
    marginTop: 4,
    textAlign: 'center',
  },
});
